server:
  port: 10001
  servlet:
    context-path: /es
spring:
  datasource:
    url: jdbc:mysql://121.196.62.153:3306/data_platform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
      log4j:
        connection-log-enabled: true
    useGlobalDataSourceStat: true

  #es配置
  elasticsearch:
    rest:
      uris: http://172.21.72.161:9200
